#!/usr/bin/env bash
# a script that installs HAProxy & makes configurations to meet the following requirements:

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5432-web
    bind *:80
    mode http
    balance roundrobin
    server 5453-web-01 54.209.164.133:80 check
    server 5453-web-02 3.93.164.216:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
